from enum import IntEnum


class Reward(IntEnum):
    REWARD_LOOSE = -10000
    REWARD_IMPOSSIBLE = -60
    REWARD_STUCK = -1000
    REWARD_PENALTY = -200
    REWARD_DEFAULT = -1
    REWARD_CHECKPOINT = 1500
    REWARD_GOAL = 60
