from typing import NewType, Dict, Tuple, List

REWARD_LOOSE = -10000
REWARD_IMPOSSIBLE = -60
REWARD_STUCK = -1000
REWARD_PENALTY = -200
REWARD_DEFAULT = -1
REWARD_CHECKPOINT = 1500
REWARD_GOAL = 60
DEFAULT_LEARNING_RATE = 0.1
DEFAULT_DISCOUNT_FACTOR = 1
SPRITE_SIZE = 64
PIPE_FREQUENCY = 30
MIN_PIPE_SIZE = 1
GAP_SIZE = 3
UP, RELEASE = 'U', 'R'
ACTIONS = [UP, RELEASE]
ABOVE, IN, UNDER, NO_PIPE = 'A', 'I', 'N', 'P'
POSITIONS = [ABOVE, IN, UNDER, NO_PIPE]
