DEFAULT_LEARNING_RATE = 0.1
DEFAULT_DISCOUNT_FACTOR = 1

SCREEN_HEIGHT = 800
SCREEN_WIDTH = 900

PIPE_FREQUENCY = 50
MIN_PIPE_SIZE = 100
GAP_SIZE = 200
PIPE_SPEED = 20

PLAYER_SPEED = 10
GRAVITY = 12
DY = 6

UP, RELEASE = 'U', 'R'
ACTIONS = [UP, RELEASE]
ABOVE, IN, UNDER, NO_PIPE = 'A', 'I', 'N', 'P'
POSITIONS = [ABOVE, IN, UNDER, NO_PIPE]

CHEAT_REWARD = True
CHEAT_LEARNING = True
